spring.application.name=ms-pagos
server.port=9097
server.address=0.0.0.0

spring.datasource.url=jdbc:mysql://localhost:3306/pagos_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Santiago
spring.datasource.username=root
spring.datasource.password=

eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

logging.file.name=logs/pago-service.log
logging.pattern.console=%d{HH:mm:ss} %-5level %msg%n
logging.pattern.file=%d{HH:mm:ss} %-5level %msg%n
logging.level.com.juratempest.ms_pagos=INFO

app.jwt.secret=${JWT_SECRET:JuraTempestArcadeHub}
