server:
  port: 9090
  address: 0.0.0.0

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-usuarios-auth
              uri: http://${MS_HOST:localhost}:9091
              predicates:
                - Path=/auth/**,/users/**

            - id: ms-maquinas
              uri: http://${MS_HOST:localhost}:9092
              predicates:
                - Path=/maquinas/**

            - id: ms-horarios
              uri: http://${MS_HOST:localhost}:9093
              predicates:
                - Path=/horarios/**

            - id: ms-reservas
              uri: http://${MS_HOST:localhost}:9094
              predicates:
                - Path=/reservas/**

            - id: ms-fidelizacion
              uri: http://${MS_HOST:localhost}:9095
              predicates:
                - Path=/fidelizacion/**

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

app:
  jwt:
    secret: ${JWT_SECRET:JuraTempestArcadeHub}
