server:
  port: 9090

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:
          routes:
            
            - id: ms-usuarios-auth
              uri: http://localhost:9091
              predicates:
                - Path=/auth/**,/users/**

            - id: ms-maquinas
              uri: http://localhost:9092
              predicates:
                - Path=/maquinas/**

            - id: ms-horarios
              uri: http://localhost:9093
              predicates:
                - Path=/horarios/**

            - id: ms_reservas
              uri: http://localhost:9094
              predicates:
                - Path=/reservas/**

            - id: ms_fidelizacion
              uri: http://localhost:9095
              predicates:
                - Path=/fidelizacion/**