server:
  port: 9090
  address: 0.0.0.0

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-usuarios
              uri: lb://ms-usuarios
              predicates:
                - Path=/users/**

            - id: ms-auth
              uri: lb://ms-auth
              predicates:
                - Path=/auth/**

            - id: ms-maquinas
              uri: lb://ms-maquinas
              predicates:
                - Path=/maquinas/**

            - id: ms-horarios
              uri: lb://ms-horarios
              predicates:
                - Path=/horarios/**

            - id: ms-reservas
              uri: lb://ms-reservas
              predicates:
                - Path=/reservas/**

            - id: ms-fidelizacion
              uri: lb://ms-fidelizacion
              predicates:
                - Path=/fidelizacion/**

            - id: ms-notificaciones
              uri: lb://ms-notificaciones
              predicates:
                - Path=/notificaciones/**

            - id: ms-pagos
              uri: lb://ms-pagos
              predicates:
                - Path=/pagos/**

            - id: ms-promociones
              uri: lb://ms-promociones
              predicates:
                - Path=/promociones/**

            - id: ms-mantenimiento
              uri: lb://ms-mantenimiento
              predicates:
                - Path=/mantenimientos/**

            - id: ms-eventos-torneos
              uri: lb://ms-eventos-torneos
              predicates:
                - Path=/torneos/**

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

app:
  jwt:
    secret: ${JWT_SECRET:JuraTempestArcadeHub}
